# Generated by Django 5.1 on 2024-08-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='name',
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='lat_end',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='lat_start',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='long_end',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='long_start',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SpeedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_readings', to='traffic.roadsegment')),
            ],
        ),
        migrations.DeleteModel(
            name='TrafficReading',
        ),
    ]
