# Generated by Django 5.1 on 2024-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_remove_roadsegment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='SpeedReading',
        ),
    ]
